---
title: "Feature grouping"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: false
    number_sections: false
    toc_float: false
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

In this document I'll perform the feature grouping.


# Parameters

```{r parameters}
polarity <- "NEG" # specify "POS" or "NEG"
d.rt <- 10
```

## Libraries

```{r libraries, message=FALSE, warning=FALSE}
library(xcms)
library(CompoundDb)
library(CluMSID)
```



# Data import

```{r import}
load(paste0("data/RData/data_XCMS_", polarity, ".RData"))
load(paste0("data/RData/MS2_library_", polarity, "_merged.RData"))

data <- featureValues(xdata, method = "sum", value = "into")
features <- data.frame(featureDefinitions(xdata)) 
features$FG <- NA

add <- read.csv("data/adducts.csv")
add <- add[add$polarity == "X" | add$polarity == polarity, ]
```


# Feature grouping

## MS2 relationships

First of all I'll consider the relationships between precursor and 
fragment ions (from DDA experiments).  

```{r ms2-relations}
features$MS2 <- NA

# order MS2 spectras by intensity
ms2int = c()
for(i in 1:length(featlist2)){
  ms2int <- c(ms2int, max(featlist2[[i]]@spectrum[,2]))
}

# seed for FG number
n <- 0

for(l in 1:length(featlist2)
){
  i <- order(-ms2int)[l]
  
  # if there is any FT which mzval match with precursor "i"....
  if(any(unlist(matchWithPpm(featlist2[[i]]@precursor, features$mzmed, 
                             ppm = 10)))){
    
    # get the info of that FT(s)
    tmp <- features[unlist(
      matchWithPpm(featlist2[[i]]@precursor, features$mzmed, ppm = 10)), ]
    
    # select those FT with the same RT than the precursor "i"
    tmp <- tmp[abs(tmp$rtmed - featlist2[[i]]@rt) < d.rt, ]
    
    # if there is >1 FT, select the one with the closest RT
    if(nrow(tmp)>1){
      tmp <- tmp[which.min(abs(tmp$rtmed - featlist2[[i]]@rt)),]
    }
    
    # get the FT name of the selected FT
    idx <- which(rownames(features)==rownames(tmp))
    
    if(any(idx)){
      n <- n + 1
      ft <- rownames(features)[idx]
      
      # check if any of the fragments is a FT
      for(j in 1:nrow(featlist2[[i]]@spectrum)){
        if(any(unlist(matchWithPpm(featlist2[[i]]@spectrum[j,1], 
                                   features$mzmed, ppm = 10)))){
          tmp <- features[unlist(matchWithPpm(
            featlist2[[i]]@spectrum[j,1], features$mzmed, ppm = 10)), ]
          tmp <- tmp[abs(tmp$rtmed - featlist2[[i]]@rt) < d.rt, ]
          if(nrow(tmp)>1){
            tmp <- tmp[which.min(abs(tmp$rtmed - featlist2[[i]]@rt)),]
          }
          idx <- c(idx, which(rownames(features)==rownames(tmp)))
        }
      }
      
      # Check correlations: (MISSING INTENSITY CORRELATIONS!!!)
      features.i <- features[idx,]
      rtr <- c(min(features.i$rtmin), max(features.i$rtmax)) + 
        d.rt * c(-1, 1)
      features.i$cor_ps <- NA
      xdata_n <- xdata
      register(SerialParam())
      chr1 <- chromatogram(
        xdata_n, mz = featlist2[[i]]@precursor + 0.01 * c(-1, 1), 
        rt = rtr, aggregationFun = "max")
      for(k in seq(nrow(features.i))){
        chr2 <- chromatogram(
          xdata_n, mz = features.i$mzmed[k] + 0.01 * c(-1, 1), 
          rt = rtr, aggregationFun = "max")
        features.i$cor_ps[k] <- xcms::correlate(
          chr1[[chromPeaks(chr1)[which.max(chromPeaks(chr1)[, "into"]), "column"]]], 
          chr2[[chromPeaks(chr2)[which.max(chromPeaks(chr2)[, "into"]), "column"]]])
      } # close EIC
      features.i$cor_ps[is.na(features.i$cor_ps)] <- 0
      features.i$cor_ps[rownames(features.i) == ft] <- 1
      features.i <- features.i[features.i$cor_ps > 0.7,]
      
      # Assign FG group:
      idx <- which(rownames(features) %in% rownames(features.i))
      if(any(!is.na(features$FG[idx]))){
        if(length(unique(features$FG[idx][!is.na(
          features$FG[idx])])) == 1){
          features$FG[idx] <- unique(features$FG[idx][!is.na(
            features$FG[idx])])
        } else {
          print(i)
        }
        n <- n-1
      } else {
        features$FG[idx] <- sprintf("FG%03d", n)
      }
      for(j in 1:length(idx)){
        if(is.na(features$MS2[idx[j]])){
          if(length(add$assignation[abs((
            features$mzmed[idx[j]] -featlist2[[i]]@precursor) - 
            add$mzdiff) < 0.001])>0){
            features$MS2[idx[j]] <- 
              paste(round(featlist2[[i]]@precursor, 4),
                    add$assignation[abs((
                      features$mzmed[idx[j]] -featlist2[[i]]@precursor) - 
                        add$mzdiff) < 0.001])
          } else {
            features$MS2[idx[j]] <- paste(
              round(featlist2[[i]]@precursor, 4), "[frag]*")
          }
        } else {
          if(length(add$assignation[abs((
            features$mzmed[idx[j]] -featlist2[[i]]@precursor) - 
            add$mzdiff) < 0.001])>0){
            features$MS2[idx[j]] <- paste(
              features$MS2[idx[j]], 
              paste(round(featlist2[[i]]@precursor, 4),
                    add$assignation[abs((
                      features$mzmed[idx[j]] -featlist2[[i]]@precursor) - 
                        add$mzdiff) < 0.001]), sep = "; ")
          } else {
            features$MS2[idx[j]] <- paste(
              features$MS2[idx[j]], 
              paste(round(featlist2[[i]]@precursor, 4), "[frag]*"), 
              sep = "; ")
          }
        }
      }
    }
  } # close "if: any(idx)" (i.e., any FT match with precursor "i")
}
```


```{r ms2-relations-2}
if(polarity == "NEG"){
  features$MS2 <- gsub("\\*", "-", features$MS2)
} else if(polarity == "POS"){
  features$MS2 <- gsub("\\*", "+", features$MS2)
}

rm(add, data, ms2int, featlist2, ft, chr1, chr2, features.i, tmp, 
   xdata_n, idx, i, l, j, k, rtr)
```



## Correlations

```{r correlations}
dt <- as.data.frame(t(featureValues(xdata, method = "sum", value = "into")))

for(z in 1:nrow(features)){ # go feature by feature ("z")
  ft <- rownames(features)[z]
  # go only in case that feature "z":
  if(is.na(features$FG[rownames(features) == ft])){ 
    # is still not located in any group
    
    n <- n + 1 # increase by 1 the code to give the current group
    
    # get data of the current feature
    z.mz <- features$mzmed[rownames(features) == ft]
    z.rt <- features$rtmed[rownames(features) == ft]
    
    # get features co-eluting with feature "z"
    features.i <- features[
      ((features$rtmin > 
          (features$rtmin[rownames(features)==ft] - (d.rt/2))) & 
         (features$rtmax) < 
         (features$rtmax[rownames(features)==ft] + (d.rt/2))),
    ]
    # correlate intensities
    if(nrow(features.i) > 1){
      
      tmp <- dt[!grepl("QC", rownames(dt)), 
                colnames(dt) %in% rownames(features.i)]
      cor.i <- c()
      for(i in seq(ncol(tmp))){
        tmp2 <- cbind(tmp[, ft], tmp[,i])
        if(sum(complete.cases(tmp2))>1){
          cor.i <- c(cor.i, cor(log2(tmp2[,1]), log2(tmp2[,2]), 
                                use = "complete.obs"))
        } else {
          cor.i <- c(cor.i, 0)
        }
      }
      features.i$cor_int <- cor.i
      features.i <- features.i[features.i$cor_int > 0.7,]
      
      # correlate peak shapes
      xdata_n <- xdata
      rtr <- c(min(features.i$rtmin), 
               max(features.i$rtmax)) + d.rt * c(-1, 1)
      features.i$cor_ps <- NA
      chr1 <- chromatogram(xdata_n, 
                           mz = z.mz + 0.01 * c(-1, 1), 
                           rt = rtr, 
                           aggregationFun = "max")
      for(i in seq(nrow(features.i))){
        chr2 <- chromatogram(xdata_n, 
                             mz = features.i$mzmed[i] + 0.01 * c(-1, 1), 
                             rt = rtr, 
                             aggregationFun = "max")
        features.i$cor_ps[i] <- correlate(chr1[[1]], chr2[[1]])
      } # close EIC
      features.i$cor_ps[is.na(features.i$cor_ps)] <- 0
      features.i$cor_ps[rownames(features.i) == ft] <- 1
      features.i <- features.i[features.i$cor_ps > 0.9,]
      
      
    }else if(nrow(features.i) == 1){
      features.i$cor_int <- 1
      features.i$cor_ps <- 1
    }
    
    
    
    # add the info of grouped peaks in results matrix
    idx <- which(rownames(features) %in% rownames(features.i))
    if(any(!is.na(features$FG[idx]))){
      if(length(unique(features$FG[idx][!is.na(
        features$FG[idx])])) == 1){
        features$FG[idx] <- unique(features.i$FG[!is.na(
          features.i$FG)])
      } else {
        tmp <- features.i[!is.na(features.i$FG),]
        idx <- which(rownames(features) %in% 
                       rownames(features.i)[is.na(features.i$FG)])
        features$FG[idx] <- tmp$FG[which.min(abs(
          z.rt - features.i$rtmed))]
      }
      n <- n-1
    } else {
      features$FG[idx] <- sprintf("FG%03d", n)
    }
    
  } # close if "is.na(cmp[z])"
  #save.image("data/RData/tmp.RData")
} # close results "z"
#rm(chr1, chr2, features.i, tmp, xdata_n, i, n, rtr, z, z.mz, z.rt, ft, 
#   idx, d.rt)
```



# Session information

```{r session}
save(features, file = paste0("data/RData/FT_", polarity, ".RData"))

Sys.time()-startpoint
devtools::session_info()
```
